apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: likes-web-app
  namespace: {{ .Values.argoNamespace | default "argocd" }}
  labels:
    {{- toYaml .Values.labels | nindent 4 }}
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  project: {{ .Values.argoProject | default "default" }}
  destination:
    namespace: likes-web-app
    server: {{ .Values.spec.destination.server }}
  source:
    repoURL: {{ .Values.spec.source.repoURL }}
    targetRevision: {{ .Values.spec.source.targetRevision }}
    path: examples/helm/likes-web-app
    helm:
      values: |
        {{- toYaml .Values | nindent 8 }}
  syncPolicy:
    automated:
      prune: true
    syncOptions:
    - CreateNamespace=true
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: litmus
  namespace: {{ .Values.argoNamespace | default "argocd" }}
  labels:
    {{- toYaml .Values.labels | nindent 4 }}
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  project: {{ .Values.argoProject | default "default" }}
  destination:
    namespace: litmus
    server: {{ .Values.spec.destination.server }}
  source:
    repoURL: {{ .Values.spec.source.repoURL }}
    targetRevision: {{ .Values.spec.source.targetRevision }}
    path: examples/helm/litmus
    helm:
      values: |
        {{- toYaml .Values | nindent 8 }}
  syncPolicy:
    automated:
      prune: true
    syncOptions:
    - CreateNamespace=true
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: istio-base
  namespace: {{ .Values.argoNamespace | default "argocd" }}
  labels:
    {{- toYaml .Values.labels | nindent 4 }}
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  project: {{ .Values.argoProject | default "default" }}
  destination:
    namespace: istio-system
    server: {{ .Values.spec.destination.server }}
  source:
    repoURL: {{ .Values.spec.source.repoURL }}
    targetRevision: {{ .Values.spec.source.targetRevision }}
    path: examples/helm/istio/base
    helm:
      values: |
        {{- toYaml .Values | nindent 8 }}
  syncPolicy:
    automated:
      prune: true
    syncOptions:
    - CreateNamespace=true
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: istiod
  namespace: {{ .Values.argoNamespace | default "argocd" }}
  labels:
    {{- toYaml .Values.labels | nindent 4 }}
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  project: {{ .Values.argoProject | default "default" }}
  destination:
    namespace: istio-system
    server: {{ .Values.spec.destination.server }}
  source:
    repoURL: {{ .Values.spec.source.repoURL }}
    targetRevision: {{ .Values.spec.source.targetRevision }}
    path: examples/helm/istio/istiod
    helm:
      values: |
        {{- toYaml .Values | nindent 8 }}
  syncPolicy:
    automated:
      prune: true
    syncOptions:
    - CreateNamespace=true
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: istio-ingress
  namespace: {{ .Values.argoNamespace | default "argocd" }}
  labels:
    {{- toYaml .Values.labels | nindent 4 }}
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  project: {{ .Values.argoProject | default "default" }}
  destination:
    namespace: istio-ingress
    server: {{ .Values.spec.destination.server }}
  source:
    repoURL: {{ .Values.spec.source.repoURL }}
    targetRevision: {{ .Values.spec.source.targetRevision }}
    path: examples/helm/istio/gateway
    helm:
      values: |
        {{- toYaml .Values | nindent 8 }}
  syncPolicy:
    automated:
      prune: true
    syncOptions:
    - CreateNamespace=true
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: otel
  namespace: {{ .Values.argoNamespace | default "argocd" }}
  labels:
    {{- toYaml .Values.labels | nindent 4 }}
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  project: {{ .Values.argoProject | default "default" }}
  destination:
    namespace: aws-otel
    server: {{ .Values.spec.destination.server }}
  source:
    repoURL: {{ .Values.spec.source.repoURL }}
    targetRevision: {{ .Values.spec.source.targetRevision }}
    path: examples/helm/otel
    helm:
      values: |
        {{- toYaml .Values | nindent 8 }}
  syncPolicy:
    automated:
      prune: true
    syncOptions:
    - CreateNamespace=true